### ISSUE TITLE
Cert_analysis.py breaks if there is no META-INF folder

### ISSUE THREAD

**Issue by TheKalin** [MobSF/Mobile-Security-Framework-MobSF#419]
## EXPLANATION OF THE ISSUE
Hello, today after update to v0.9.5.2 Beta I have run into issue described below.   
1. Yesterday I  have done a scan of the app.
2. Today after update I wanted to check if it everything works fine. 
3. The scan of the same apk file resulted in error.  

I have noticed a strange behaviour, fro this specific apk file /META-INF/ is not being created. And I don`t know why.  If you want I can perform some additional tests, just tell me what to do :) 
PS:
I have done a clean install from repo but it did not  work either. 
PS2: I cant share that apk file with you ;x 
## STEPS TO REPRODUCE THE ISSUE

```
1.Remove META-INF dir and run static analyzer
```

## CONSOLE OUTPUT

```
[INFO] Reading Code Signing Certificate

[2017-05-30 12:00:58]
[ERROR] Reading Code Signing Certificate (/home/kalin/MobSF/StaticAnalyzer/views/android/cert_analysis.py, LINE 49 "cert) if os.path.isfile(os.path.join(cert, f))]"): [Errno 2] No such file or directory: '/home/kalin/MobSF/uploads/27f2e6e139745f0b6150425e66e3b0be/META-INF/'
[INFO] DEX -> JAR
[...]
[INFO] Saving to Database

[2017-05-30 12:02:04]
[ERROR] Saving to DB (/home/kalin/MobSF/StaticAnalyzer/views/android/db_interaction.py, LINE 222 "CERT_INFO=cert_dic['cert_info'],"): 'NoneType' object has no attribute '__getitem__'

[2017-05-30 12:02:04]
[ERROR] Rendering to Template (/home/kalin/MobSF/StaticAnalyzer/views/android/db_interaction.py, LINE 105 "'certinfo': cert_dic['cert_info'],"): 'NoneType' object has no attribute '__getitem__'

[2017-05-30 12:02:04]
[ERROR] Static Analyzer (/home/kalin/MobSF/StaticAnalyzer/views/android/static_analyzer.py, LINE 212 "return render(request, template, context)"): 'NoneType' object has no attribute 'get'
[30/May/2017 12:02:04] "GET /StaticAnalyzer/?name=base.apk&type=apk&checksum=27f2e6e139745f0b6150425e66e3b0be HTTP/1.1" 200 4679



```

**Comment by ajinabraham** [comment]
MobSF expects a signed APK with certs.

**Comment by alienwithin** [comment]
I get a similar issue with MobSF 0.9.5.2 : 

[ERROR] Saving to DB (C:\Home\scripts\Mobile-Security-Framework-MobSF-0.9.5.2\Mobile-Security-Framework-MobSF-0.9.5.2\StaticAnalyzer\views\android\db_interaction.py, LINE 222 "CERT_INFO=cert_dic['cert_info'],"): 'NoneType' object has no attribute '__getitem__'
[2017-06-12 12:10:50]

[ERROR] Static Analyzer (C:\Home\scripts\Mobile-Security-Framework-MobSF-0.9.5.2\Mobile-Security-Framework-MobSF-0.9.5.2\StaticAnalyzer\views\android\static_analyzer.py, LINE 212 "return render(request, template, context)"): 'NoneType' object has no attribute 'get'

**Comment by CapitanShinChan** [comment]
I have the same issue here. Is there any workarround?

**Comment by ajinabraham** [comment]
MobSF expects a signed APK that has a `META-INF` directory. Do you have a sample that cause the issue

**Comment by amiralkizaru** [comment]
@ajinabraham 
https://github.com/tjunxiang92/Android-Vulnerabilities/blob/master/diva-beta.apk
this apk cause the issue

**Comment by ajinabraham** [comment]
This APK is invalid. It won't even get installed on modern android devices or VM since it lacks the Code Sining certificate in `META-INF` .
<img width="422" alt="Screenshot 2019-11-17 at 1 27 25 PM" src="https://user-images.githubusercontent.com/4301109/69011952-3af55380-093e-11ea-8290-14a642fa6b85.png">

 Attached is a valid APK.
[diva-beta.apk.zip](https://github.com/MobSF/Mobile-Security-Framework-MobSF/files/3855941/diva-beta.apk.zip)
