### ISSUE TITLE
Not working with Django 4.0

### ISSUE THREAD

**Issue by thelicato** [MobSF/Mobile-Security-Framework-MobSF#1862]
## ENVIRONMENT

```
OS and Version: Windows 11
Python Version: 3.9.5
MobSF Version: 3.4 beta
```

## EXPLANATION OF THE ISSUE

*What happens:*
There are some errors during the **setup** phase (I have all the requirements correctly installed) and when running it breaks with the error:
```
ImportError at /
cannot import name 'url' from 'django.conf.urls
```
After some research, I found out that **just today** *Django 4.0* has been released. Probably they changed something and your code broke. In fact, changing the Django version in the **requirements.txt** file to 
```
django==3.15 (instead of django>=3.1.5) 
```
solves the problem.

## STEPS TO REPRODUCE THE ISSUE

```
1. clone the repo (git clone https://github.com/MobSF/Mobile-Security-Framework-MobSF)
2. Run the setup script (setup.bat)
3. Run MobSF (run.bat 127.0.0.1 <port_number>)
```

## LOG FILE

Unfortunately I do not have the log file because I deleted the old venv (the one with Django 4.0)

**Comment by MoroccanTea** [comment]
I confirm this issue for Linux as well  running parrot 5.14.0-9parrot1-amd64 #1 SMP Debian 5.14.9-9parrot1 (2021-10-26) x86_64 GNU/Linux

**CONSOLE ERROR**
When running the run.sh script everything is in order, however as soon as I open the web app to start working I get this :
[2021-12-08 09:11:35 +0100] [245843] [INFO] Starting gunicorn 20.1.0
[2021-12-08 09:11:35 +0100] [245843] [INFO] Listening at: http://127.0.0.1:1337 (245843)
[2021-12-08 09:11:35 +0100] [245843] [INFO] Using worker: gthread
[2021-12-08 09:11:35 +0100] [245844] [INFO] Booting worker with pid: 245844
[ERROR] 08/Dec/2021 08:13:07 - Internal Server Error: /
Traceback (most recent call last):
  File "/home/moroccantea/Downloads/MobSF/Mobile-Security-Framework-MobSF-3.4.3/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/moroccantea/Downloads/MobSF/Mobile-Security-Framework-MobSF-3.4.3/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 167, in _get_response
    callback, callback_args, callback_kwargs = self.resolve_request(request)
  File "/home/moroccantea/Downloads/MobSF/Mobile-Security-Framework-MobSF-3.4.3/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 290, in resolve_request
    resolver_match = resolver.resolve(request.path_info)
  File "/home/moroccantea/Downloads/MobSF/Mobile-Security-Framework-MobSF-3.4.3/venv/lib/python3.9/site-packages/django/urls/resolvers.py", line 590, in resolve
    for pattern in self.url_patterns:
  File "/home/moroccantea/Downloads/MobSF/Mobile-Security-Framework-MobSF-3.4.3/venv/lib/python3.9/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/moroccantea/Downloads/MobSF/Mobile-Security-Framework-MobSF-3.4.3/venv/lib/python3.9/site-packages/django/urls/resolvers.py", line 632, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/moroccantea/Downloads/MobSF/Mobile-Security-Framework-MobSF-3.4.3/venv/lib/python3.9/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/moroccantea/Downloads/MobSF/Mobile-Security-Framework-MobSF-3.4.3/venv/lib/python3.9/site-packages/django/urls/resolvers.py", line 625, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/moroccantea/Downloads/MobSF/Mobile-Security-Framework-MobSF-3.4.3/mobsf/MobSF/urls.py", line 1, in <module>
    from django.conf.urls import url
ImportError: cannot import name 'url' from 'django.conf.urls' (/home/moroccantea/Downloads/MobSF/Mobile-Security-Framework-MobSF-3.4.3/venv/lib/python3.9/site-packages/django/conf/urls/__init__.py)
[ERROR] 08/Dec/2021 08:13:09 - Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/home/moroccantea/Downloads/MobSF/Mobile-Security-Framework-MobSF-3.4.3/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/moroccantea/Downloads/MobSF/Mobile-Security-Framework-MobSF-3.4.3/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 167, in _get_response
    callback, callback_args, callback_kwargs = self.resolve_request(request)
  File "/home/moroccantea/Downloads/MobSF/Mobile-Security-Framework-MobSF-3.4.3/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 290, in resolve_request
    resolver_match = resolver.resolve(request.path_info)
  File "/home/moroccantea/Downloads/MobSF/Mobile-Security-Framework-MobSF-3.4.3/venv/lib/python3.9/site-packages/django/urls/resolvers.py", line 590, in resolve
    for pattern in self.url_patterns:
  File "/home/moroccantea/Downloads/MobSF/Mobile-Security-Framework-MobSF-3.4.3/venv/lib/python3.9/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/moroccantea/Downloads/MobSF/Mobile-Security-Framework-MobSF-3.4.3/venv/lib/python3.9/site-packages/django/urls/resolvers.py", line 632, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/moroccantea/Downloads/MobSF/Mobile-Security-Framework-MobSF-3.4.3/venv/lib/python3.9/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/moroccantea/Downloads/MobSF/Mobile-Security-Framework-MobSF-3.4.3/venv/lib/python3.9/site-packages/django/urls/resolvers.py", line 625, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/moroccantea/Downloads/MobSF/Mobile-Security-Framework-MobSF-3.4.3/mobsf/MobSF/urls.py", line 1, in <module>
    from django.conf.urls import url
ImportError: cannot import name 'url' from 'django.conf.urls' (/home/moroccantea/Downloads/MobSF/Mobile-Security-Framework-MobSF-3.4.3/venv/lib/python3.9/site-packages/django/conf/urls/__init__.py)
**END OF CONSOLE ERROR**


I do not even know where it's getting django version 4.0 from i uninstalled an earlier version and it still chooses that one...

This is what the app looks like

![image](https://user-images.githubusercontent.com/58166226/145172818-01e7e261-1380-45e7-83d0-d87a833f7e16.png)

**Comment by Berthelmaster** [comment]
Same issue here! :(

**Comment by Berthelmaster** [comment]
Can you explain how you fixed the issue exactly?

**Comment by stormfleet** [comment]
Courtesy of a colleague, run as root in the MobSF directory
```
source venv/bin/activate
pip uninstall Django
pip install 'Django<4'
```

**Comment by ajinabraham** [comment]
Fixed in latest master by https://github.com/MobSF/Mobile-Security-Framework-MobSF/pull/1863
