### ISSUE TITLE
Error running on windows 

### ISSUE THREAD

**Issue by exploitprotocol** [MobSF/Mobile-Security-Framework-MobSF#322]
Hi there,

Below is the error i received when i try to run on windows 8.1 Enterprise

~~~~
C:\MobSf
> python manage.py runserver
[INFO] Running first time setup for windows.
[*] Reading config file..
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "C:\PentestBox\base\python\Lib\site-packages\django\core\management\__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "C:\PentestBox\base\python\Lib\site-packages\django\core\management\__init__.py", line 316, in execute
    settings.INSTALLED_APPS
  File "C:\PentestBox\base\python\Lib\site-packages\django\conf\__init__.py", line 53, in __getattr__
    self._setup(name)
  File "C:\PentestBox\base\python\Lib\site-packages\django\conf\__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "C:\PentestBox\base\python\Lib\site-packages\django\conf\__init__.py", line 97, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "C:\PentestBox\base\python\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "C:\MobSf\MobSF\settings.py", line 378, in <module>
    windows_setup.install_locally(MobSF_HOME)
  File "C:\MobSf\install\windows\setup.py", line 397, in install_locally
    rewrite_config()
  File "C:\MobSf\install\windows\setup.py", line 372, in rewrite_config
    CONFIG['MobSF']['dir'] = expanduser("~") + CONFIG['MobSF']['dir']
AttributeError: ConfigParser instance has no attribute '__getitem__'
~~~~

I am running with admin privileges.

**Comment by ajinabraham** [comment]
@DominikSchlecht Any hints?

**Comment by DominikSchlecht** [comment]
Could you please run the expanduser("~")  in an administrator shell. Maybe it does not have a profile path?

Otherwise I have no idea right now :/

LG,
Dominik

**Comment by RoyMobsf** [comment]
1. install python https://www.python.org/ftp/python/2.7/python-2.7.amd64.msi
2. set the path
3. install https://www.microsoft.com/en-us/download/confirmation.aspx?id=44266

Https://pypi.python.org/pypi/lxml/3.6.0#downloads
Download library
That I did not take
Pip install the rest
And correct that mistake
Ready, I'm walking

The stack overflow post http://stackoverflow.com/questions/16259729/django-python-manage-py-runserver-gives-runtimeerror-maximum-recursion-depth-e

**Comment by exploitprotocol** [comment]
I already had the required libraries @RoyMobsf , still not working

**Comment by RoyMobsf** [comment]
The one who invented this could not pack it up so we do not have so many headaches that the madman

**Comment by exploitprotocol** [comment]
@RoyMobsf you should respect the person(@ajinabraham) who is trying to manage a project with no gains and helping others. It is quite difficult to maintain open source project while maintaining work/life balance. 

I hope you will understand that @RoyMobsf

**Comment by DominikSchlecht** [comment]
So it seems like the config file is not where it is meant to be.

With a feature request some time ago all config files were moved to the users profile folder.

As I already posted, could you please check if your administrator has a profile? In enterprises this is sometimes disabled.

If the admin-user has a profile, please check if the config files are in place (`C:\Users\Administrators\MobSF\config` if I remember right.

Greetings,
Dominik (The madman implementing this part ;))

**Comment by exploitprotocol** [comment]
Hi @DominikSchlecht ,

Actually i was using mobsf inside pentestbox, and the older version(0.9.2) version used to work fine. But when i updated to 0.9.3, it stopped working. Tried everything.

But when i tried with independent python installation then it worked . But now i am experiencing something different, i am able to start the server, upload is working fine and analysis is also working fine in the terminal but after completion of analysis it gets error page.

~~~~
Don't Play Around. An Error just popped in!
'NoneType' object has no attribute '__getitem__'

Inappropriate argument type.
~~~~

Yeah the config file is present in C:\Users\Aditya\MobSF\config\

**Comment by DominikSchlecht** [comment]
Thats strange o0

Is there anything on the console?
Which type of analysis are you running (android/windows-phone/iOS)?

**Comment by exploitprotocol** [comment]
I am trying to analyze some apk file, interesting thing is all the apk are getting analyzed by the mobsf but only one results is shown(I am analyzing individually)

**Comment by ajinabraham** [comment]
I think your db migration failed 
Share your console log. Just need to identify where the error occurred 
Also check https://github.com/MobSF/Mobile-Security-Framework-MobSF/wiki/1.-Documentation#updating-mobsf

**Comment by exploitprotocol** [comment]
I did both `makemigrations` and `migrate` before running.

After processing this is theline which gives out error

~~~

[2017-01-31 01:53:32]
[ERROR] Static Analyzer (C:\mobsf\StaticAnalyzer\views\android\static_analyzer.p
y, LINE 157 "man_an_dic['permissons'],"): 'NoneType' object has no attribute '__
getitem__'
~~~

**Comment by ajinabraham** [comment]
This early is a db migration  error.  Just to confirm  this set USE_HOME=True in your settings. py

**Comment by ajinabraham** [comment]
Also you can expect  errors on previously scanned apks, after u Migrate db

**Comment by exploitprotocol** [comment]
I have just set USE_HOME=True and below is the error after that

~~~~

C:\mobsf>C:/Python27/python.exe manage.py makemigrations

[2017-01-31 02:00:36]
[ERROR] Parsing Config (C:\mobsf\MobSF\settings.py, LINE 85 "sett = imp.load_sou
rce('user_settings', USER_CONFIG)"): expected an indented block (config.py, line
 122)
[INFO] Running first time setup for windows.
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Python27\lib\site-packages\django\core\management\__init__.py", line
367, in execute_from_command_line
    utility.execute()
  File "C:\Python27\lib\site-packages\django\core\management\__init__.py", line
316, in execute
    settings.INSTALLED_APPS
  File "C:\Python27\lib\site-packages\django\conf\__init__.py", line 53, in __ge
tattr__
    self._setup(name)
  File "C:\Python27\lib\site-packages\django\conf\__init__.py", line 41, in _set
up
    self._wrapped = Settings(settings_module)
  File "C:\Python27\lib\site-packages\django\conf\__init__.py", line 97, in __in
it__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "C:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "C:\mobsf\MobSF\settings.py", line 379, in <module>
    windows_setup.install_locally(MobSF_HOME)
  File "C:\mobsf\install\windows\setup.py", line 393, in install_locally
    local_config(mobsf_home)
  File "C:\mobsf\install\windows\setup.py", line 356, in local_config
    os.path.join(CONFIG_PATH, CONFIG_FILE)
  File "C:\Python27\lib\shutil.py", line 119, in copy
    copyfile(src, dst)
  File "C:\Python27\lib\shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: 'C:\\Users\\Aditya\\.MobSF\\instal
l\\windows\\config.txt'
~~~~

**Comment by DominikSchlecht** [comment]
Hmm to be honest I didn't try the migrate command with the local install routine.. (Didn't migrate until now, since I normally just pull a fresh new version. Maybe we should start writing test-cases ^^)

I will debug this tomorrow and try to introduce a fix.

Greetings,
Dominik

**Comment by ajinabraham** [comment]
Unit test is some thing I missed to write all this time.

**Comment by DominikSchlecht** [comment]
This should fix the error with the path. It would be great if you could confirm the fix.

Since this issue was already used for 2 different issues, please open a new one if there are other issues :)

Greetings,
Dominik

**Comment by ajinabraham** [comment]
@exploitprotocol Can you please verify this with `USE_HOME=True` ?

**Comment by exploitprotocol** [comment]
@DominikSchlecht @ajinabraham I am still getting the same error, tried USE_HOME =True as well.

**Comment by DominikSchlecht** [comment]
Could you please verify that setup.py in line 353 holds:
```
# Copy predefined config to MobSF folder
    shutil.copy(
        os.getcwd() + "\\install\\windows\\config.txt",
        os.path.join(CONFIG_PATH, CONFIG_FILE)
    )
```

**Comment by exploitprotocol** [comment]
Yup those lines are there
~~~~
[2017-02-02 03:35:48]
[ERROR] Static Analyzer (C:\mobsf\StaticAnalyzer\views\android\static_analyzer.p
y, LINE 157 "man_an_dic['permissons'],"): 'NoneType' object has no attribute '__
getitem__'
~~~~
This is the error after analyzing.
Mobsf 0.9.2 is still working fine on my system.

**Comment by DominikSchlecht** [comment]
Yeah but this is a different error ^^

Looks like #331

**Comment by ajinabraham** [comment]
@exploitprotocol 
I have bumped MobSF version with few updates.

Can you try deleting your existing MobSF files including DB. Clone a new copy of MobSF from master and try again. If you still see the problem, share the APK that caused the problem.
